if [ -f /sbin/.magisk/mirror/system/etc/fonts.xml ]; then
    mkdir -p $MODPATH/system/fonts && mkdir $MODPATH/system/etc/
    cp -af /sbin/.magisk/mirror/system/etc/fonts.xml $MODPATH/system/etc/fonts.xml
else
    abort "fonts.xml not found! Cancel instation."
fi

if [ -f /sdcard/Download/NotoSansCJK.ttc ] && [ -f /sdcard/Download/NotoSerifCJK.ttc ]; then
    cp -af /sdcard/Download/NotoSansCJK.ttc $MODPATH/system/fonts/ && cp -af /sdcard/Download/NotoSerifCJK.ttc $MODPATH/system/fonts/
elif [ -f /sdcard/Download/NotoSansCJK.ttc ] && [ "$API" -lt "28" ]; then
    cp -af /sdcard/Download/NotoSansCJK.ttc $MODPATH/system/fonts/
else
    abort "Please download and put NotoSansCJK.ttc & NotoSerifCJK.ttc(for API28+) to /sdcard/Download/!"
fi

if [ -f $MIRRORPATH$FILEPATH$FILE ]; then
sed -i '
    /<family lang=\"zh-Hans\">/,/<\/family>/ {/<\/family>/! d;
    /<\/family>/ s/.*/    <family lang="zh-Hans">\n        <font weight="100" style="normal" index="2">NotoSansCJK.ttc<\/font>\n        <font weight="300" style="normal" index="6">NotoSansCJK.ttc<\/font>\n        <font weight="350" style="normal" index="10">NotoSansCJK.ttc<\/font>\n        <font weight="400" style="normal" index="14">NotoSansCJK.ttc<\/font>\n        <font weight="500" style="normal" index="22">NotoSansCJK.ttc<\/font>\n        <font weight="700" style="normal" index="26">NotoSansCJK.ttc<\/font>\n        <font weight="900" style="normal" index="34">NotoSansCJK.ttc<\/font>\n        <font weight="400" style="normal" index="18" fallbackFor="monospace">NotoSansCJK.ttc<\/font>\n        <font weight="700" style="normal" index="30" fallbackFor="monospace">NotoSansCJK.ttc<\/font>\n        <font weight="200" style="normal" index="2" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="300" style="normal" index="6" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="400" style="normal" index="10" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="500" style="normal" index="14" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="600" style="normal" index="18" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="700" style="normal" index="22" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="900" style="normal" index="26" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n    <\/family>/};
    /<family lang=\"zh-Hant zh-Bopo\">/,/<\/family>/ {/<\/family>/! d;
    /<\/family>/ s/.*/    <family lang="zh-Hant zh-Bopo">\n        <font weight="100" style="normal" index="3">NotoSansCJK.ttc<\/font>\n        <font weight="300" style="normal" index="7">NotoSansCJK.ttc<\/font>\n        <font weight="350" style="normal" index="11">NotoSansCJK.ttc<\/font>\n        <font weight="400" style="normal" index="15">NotoSansCJK.ttc<\/font>\n        <font weight="500" style="normal" index="23">NotoSansCJK.ttc<\/font>\n        <font weight="700" style="normal" index="27">NotoSansCJK.ttc<\/font>\n        <font weight="900" style="normal" index="35">NotoSansCJK.ttc<\/font>\n        <font weight="400" style="normal" index="19" fallbackFor="monospace">NotoSansCJK.ttc<\/font>\n        <font weight="700" style="normal" index="31" fallbackFor="monospace">NotoSansCJK.ttc<\/font>\n        <font weight="200" style="normal" index="3" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="300" style="normal" index="7" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="400" style="normal" index="11" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="500" style="normal" index="15" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="600" style="normal" index="19" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="700" style="normal" index="23" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="900" style="normal" index="27" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n    <\/family>/};
    /<family lang=\"zh-Hant,zh-Bopo\">/,/<\/family>/ {/<\/family>/! d;
    /<\/family>/ s/.*/    <family lang="zh-Hant,zh-Bopo">\n        <font weight="100" style="normal" index="3">NotoSansCJK.ttc<\/font>\n        <font weight="300" style="normal" index="7">NotoSansCJK.ttc<\/font>\n        <font weight="350" style="normal" index="11">NotoSansCJK.ttc<\/font>\n        <font weight="400" style="normal" index="15">NotoSansCJK.ttc<\/font>\n        <font weight="500" style="normal" index="23">NotoSansCJK.ttc<\/font>\n        <font weight="700" style="normal" index="27">NotoSansCJK.ttc<\/font>\n        <font weight="900" style="normal" index="35">NotoSansCJK.ttc<\/font>\n        <font weight="400" style="normal" index="19" fallbackFor="monospace">NotoSansCJK.ttc<\/font>\n        <font weight="700" style="normal" index="31" fallbackFor="monospace">NotoSansCJK.ttc<\/font>\n        <font weight="200" style="normal" index="3" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="300" style="normal" index="7" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="400" style="normal" index="11" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="500" style="normal" index="15" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="600" style="normal" index="19" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="700" style="normal" index="23" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="900" style="normal" index="27" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n    <\/family>/};
    /<family lang=\"ja\">/,/<\/family>/ {/<\/family>/! d;
    /<\/family>/ s/.*/    <family lang="ja">\n        <font weight="100" style="normal" index="0">NotoSansCJK.ttc<\/font>\n        <font weight="300" style="normal" index="4">NotoSansCJK.ttc<\/font>\n        <font weight="350" style="normal" index="8">NotoSansCJK.ttc<\/font>\n        <font weight="400" style="normal" index="12">NotoSansCJK.ttc<\/font>\n        <font weight="500" style="normal" index="20">NotoSansCJK.ttc<\/font>\n        <font weight="700" style="normal" index="24">NotoSansCJK.ttc<\/font>\n        <font weight="900" style="normal" index="32">NotoSansCJK.ttc<\/font>\n        <font weight="400" style="normal" index="16" fallbackFor="monospace">NotoSansCJK.ttc<\/font>\n        <font weight="700" style="normal" index="28" fallbackFor="monospace">NotoSansCJK.ttc<\/font>\n        <font weight="200" style="normal" index="0" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="300" style="normal" index="4" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="400" style="normal" index="8" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="500" style="normal" index="12" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="600" style="normal" index="16" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="700" style="normal" index="20" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="900" style="normal" index="24" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n    <\/family>/};
    /<family lang=\"ko\">/,/<\/family>/ {/<\/family>/! d;
    /<\/family>/ s/.*/    <family lang="ko">\n        <font weight="100" style="normal" index="1">NotoSansCJK.ttc<\/font>\n        <font weight="300" style="normal" index="5">NotoSansCJK.ttc<\/font>\n        <font weight="350" style="normal" index="9">NotoSansCJK.ttc<\/font>\n        <font weight="400" style="normal" index="13">NotoSansCJK.ttc<\/font>\n        <font weight="500" style="normal" index="21">NotoSansCJK.ttc<\/font>\n        <font weight="700" style="normal" index="25">NotoSansCJK.ttc<\/font>\n        <font weight="900" style="normal" index="33">NotoSansCJK.ttc<\/font>\n        <font weight="400" style="normal" index="17" fallbackFor="monospace">NotoSansCJK.ttc<\/font>\n        <font weight="700" style="normal" index="29" fallbackFor="monospace">NotoSansCJK.ttc<\/font>\n        <font weight="200" style="normal" index="1" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="300" style="normal" index="5" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="400" style="normal" index="9" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="500" style="normal" index="13" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="600" style="normal" index="17" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="700" style="normal" index="21" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n        <font weight="900" style="normal" index="25" fallbackFor="serif">NotoSerifCJK.ttc<\/font>\n    <\/family>\n    <alias name="sans-serif-demi-light" to="sans-serif" weight="350" />\n    <alias name="serif-extra-light" to="serif" weight="200" />\n    <alias name="serif-light" to="serif" weight="300" />\n    <alias name="serif-medium" to="serif" weight="500" />\n    <alias name="serif-semi-bold" to="serif" weight="600" />\n    <alias name="serif-bold" to="serif" weight="700" />\n    <alias name="serif-black" to="serif" weight="900" />/};
    /^$/d' $MODPATH/system/etc/fonts.xml
elif [ "$API" -ge "24" ]; then
sed -i '
    /<family lang=\"zh-Hans\">/,/<\/family>/ {/<\/family>/! d;
    /<\/family>/ s/.*/    <family lang="zh-Hans">\n        <font weight="100" style="normal" index="2">NotoSansCJK.ttc<\/font>\n        <font weight="300" style="normal" index="6">NotoSansCJK.ttc<\/font>\n        <font weight="350" style="normal" index="10">NotoSansCJK.ttc<\/font>\n        <font weight="400" style="normal" index="14">NotoSansCJK.ttc<\/font>\n        <font weight="500" style="normal" index="22">NotoSansCJK.ttc<\/font>\n        <font weight="700" style="normal" index="26">NotoSansCJK.ttc<\/font>\n        <font weight="900" style="normal" index="34">NotoSansCJK.ttc<\/font>\n    <\/family>/};
    /<family lang=\"zh-Hant\">/,/<\/family>/ {/<\/family>/! d;
    /<\/family>/ s/.*/    <family lang="zh-Hant">\n        <font weight="100" style="normal" index="3">NotoSansCJK.ttc<\/font>\n        <font weight="300" style="normal" index="7">NotoSansCJK.ttc<\/font>\n        <font weight="350" style="normal" index="11">NotoSansCJK.ttc<\/font>\n        <font weight="400" style="normal" index="15">NotoSansCJK.ttc<\/font>\n        <font weight="500" style="normal" index="23">NotoSansCJK.ttc<\/font>\n        <font weight="700" style="normal" index="27">NotoSansCJK.ttc<\/font>\n        <font weight="900" style="normal" index="35">NotoSansCJK.ttc<\/font>\n    <\/family>/};
    /<family lang=\"ja\">/,/<\/family>/ {/<\/family>/! d;
    /<\/family>/ s/.*/    <family lang="ja">\n        <font weight="100" style="normal" index="0">NotoSansCJK.ttc<\/font>\n        <font weight="300" style="normal" index="4">NotoSansCJK.ttc<\/font>\n        <font weight="350" style="normal" index="8">NotoSansCJK.ttc<\/font>\n        <font weight="400" style="normal" index="12">NotoSansCJK.ttc<\/font>\n        <font weight="500" style="normal" index="20">NotoSansCJK.ttc<\/font>\n        <font weight="700" style="normal" index="24">NotoSansCJK.ttc<\/font>\n        <font weight="900" style="normal" index="32">NotoSansCJK.ttc<\/font>\n    <\/family>/};
    /<family lang=\"ko\">/,/<\/family>/ {/<\/family>/! d;
    /<\/family>/ s/.*/    <family lang="ko">\n        <font weight="100" style="normal" index="1">NotoSansCJK.ttc<\/font>\n        <font weight="300" style="normal" index="5">NotoSansCJK.ttc<\/font>\n        <font weight="350" style="normal" index="9">NotoSansCJK.ttc<\/font>\n        <font weight="400" style="normal" index="13">NotoSansCJK.ttc<\/font>\n        <font weight="500" style="normal" index="21">NotoSansCJK.ttc<\/font>\n        <font weight="700" style="normal" index="25">NotoSansCJK.ttc<\/font>\n        <font weight="900" style="normal" index="33">NotoSansCJK.ttc<\/font>\n    <\/family>\n    <alias name="sans-serif-demi-light" to="sans-serif" weight="350" />/};
    /^$/d' $MODPATH/system/etc/fonts.xml
else
    abort "The version (API${API}) of your Android doesn't support super OTC!"
fi

set_perm_recursive $MODPATH 0 0 0755 0644
